info:
  name: ${project.artifactId}
  version: ${project.version}
  origin: ${scm.url}
  commit: ${buildNumber}
  branch: ${scmBranch}
  built: ${timestamp}

# logging config here as a reminder as to how to override logback from cmd line
# ie -Dlogging.level.org.springframework=DEBUG
logging:
  level:
    uk.gov.ons.ctp: DEBUG
    org.springframework: ERROR
  profile: DEV
  useJson: false


management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure:
        include: info, health
  endpoint:
    info:
      enabled: true 
    health:
      enabled: true
  metrics:
    tags:
      application: MockEnvoy
      pod: ${HOSTNAME}
    export:
      stackdriver:
        project-id: ${GOOGLE_CLOUD_PROJECT}
        enabled: false
        step: PT2M

server:
  port: 8181

spring:
  mvc:
    servlet:
      path: /
  output:
    ansi:
      enabled: never
  application:
    name: ONS SdcIntMockEnvoy

