apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-envoy
  labels:
    app: mock-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-envoy
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: mock-envoy
      labels:
        app: mock-envoy
    spec:
      containers:
      - name: mock-envoy
        image: europe-west2-docker.pkg.dev/ons-ci-int/int-docker-snapshot/mock-envoy:SOC-32_Initial_version_of_mock_envoy
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1000m"
            memory: "1000Mi"
          limits:
            cpu: "1000m"
            memory: "1000Mi"
        readinessProbe:
          httpGet:
            path: /info
            port: 8181
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /info
            port: 8181
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        ports:
        - name: http-server
          containerPort: 8181
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Dlogging.useJson=true
            -Dspring.profiles.active=dev"
