apiVersion: v1
kind: Service
metadata:
  name: mock-envoy
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"mock-envoy-ingress"}}'
  labels:
    app: mock-envoy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http-server
  selector:
    app: mock-envoy
